// priority: 1000

const materialsList = [
    {id: 'wood', raw_resource: 'born_in_chaos_v1:scorched_planks'},
    {id: 'clay', raw_resource: 'clay_ball'},
    {id: 'flint', raw_resource: 'flint'},
    {id: 'porcelain', raw_resource: 'ceramics:porcelain_brick'},
    {id: 'terracotta', raw_resource: 'terracotta'},
    {id: 'stone', raw_resource: 'stone'},
    {id: 'bone', raw_resource: 'bone'},
    {id: 'mud', raw_resource: 'kubejs:mud_brick'},
    {id: 'fine_wood', raw_resource: 'supplementaries:fine_wood'},
    {id: 'ash', raw_resource: 'supplementaries:ash_brick'},
    {id: 'brick', raw_resource: 'minecraft:brick'},
    {id: 'copper', raw_resource: 'minecraft:copper_ingot'},
    {id: 'tin', raw_resource: 'thermal:tin_ingot'},
    {id: 'coal', raw_resource: 'minecraft:coal'},
    {id: 'ancient_wood', raw_resource: 'naturesaura:ancient_log'},
    {id: 'smooth_stone', raw_resource: 'minecraft:smooth_stone'},
    {id: 'dripstone', raw_resource: 'minecraft:dripstone_block'},
    {id: 'kivi', raw_resource: 'xycraft_world:kivi'},
    {id: 'caminite', raw_resource: 'embers:caminite_brick'},
    {id: 'raw_caminite', raw_resource: 'embers:caminite_blend'},
    {id: 'granite', raw_resource: 'polished_granite'},
    {id: 'diorite', raw_resource: 'polished_diorite'},
    {id: 'andesite', raw_resource: 'polished_andesite'},
    {id: 'limestone', raw_resource: 'create:limestone'},
    {id: 'scoria', raw_resource: 'create:scoria'},
    {id: 'basalt', raw_resource: 'smooth_basalt'},
    {id: 'calcite', raw_resource: 'quark:polished_calcite'},
    {id: 'deepslate', raw_resource: 'polished_deepslate'},
]
global.materialsList = materialsList