ServerEvents.recipes(event => {
    event.remove({output: 'confluence:copper_watch'})
    event.remove({output: 'confluence:tin_watch'})
    event.remove({output: 'confluence:silver_watch'})
    event.remove({output: 'confluence:tungsten_watch'})
    event.remove({output: 'confluence:gold_watch'})
    event.remove({output: 'confluence:platinum_watch'})
    event.remove({output: 'confluence:stopwatch'})
    event.remove({output: 'confluence:magic_mirror'})
})