
["Accessibility Settings"]
	#Enable or disable camera shaking effects (Turn off if you experience motion sickness).
	enableCameraShake = true
	#Enable or disable dynamic FOV changes caused by mod items and effects.
	enableFovEffects = true

