#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jan 19 17:10:40 EST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=
enableShaders=false
