#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jan 21 19:40:26 EST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=
enableShaders=false
