#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Apr 12 11:53:47 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=
enableShaders=true
